steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/email-processor', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/email-processor']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'email-processor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/email-processor'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
        SUPABASE_URL=${_SUPABASE_URL},
        SUPABASE_KEY=${_SUPABASE_KEY},
        GEMINI_API_KEY=${_GEMINI_API_KEY},
        FRONTEND_URL=${_FRONTEND_URL},
        MANUAL_SYNC_API_KEY=${_MANUAL_SYNC_API_KEY}
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'

# Substitution variables (set in Cloud Build trigger or via command line)
substitutions:
  _SUPABASE_URL: ''
  _SUPABASE_KEY: ''
  _GEMINI_API_KEY: ''
  _FRONTEND_URL: 'https://resumeforge.vercel.app'
  _MANUAL_SYNC_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY